In [ ]:
# Importer librairies standards
import pandas as pd
import numpy as np
import math
import bs4 as bs
import urllib.request
import matplotlib.pyplot as plt
import seaborn as sns
import ipywidgets as widgets
from ipywidgets import interact, interact_manual

In [ ]:
# Téléchargement des datasets
interactions_train = pd.read_csv('https://raw.githubusercontent.com/Vane-s/UNIL_Rolex/main/interactions_train.csv')
items = pd.read_csv("https://raw.githubusercontent.com/Vane-s/UNIL_Rolex/main/items.csv")
# Les premières lignes de chaque dataset
display(interactions_train.head())
display(items.head())

      u      i             t
0  4456   8581  1.687541e+09
1   142   1964  1.679585e+09
2   362   3705  1.706872e+09
3  1809  11317  1.673533e+09
4  4384   1323  1.681402e+09

,Title,Author,ISBN Valid,Publisher,Subjects,i
0,Classification décimale universelle : édition ...,NaN,9782871303336; 2871303339,Ed du CEFAL,Classification décimale universelle; Indexatio...,0
1,Les interactions dans l'enseignement des langu...,"Cicurel, Francine, 1947-",9782278058327; 2278058320,Didier,didactique--langue étrangère - enseignement; d...,1
2,Histoire de vie et recherche biographique : pe...,NaN,2343190194; 9782343190198,L'Harmattan,Histoires de vie en sociologie; Sciences socia...,2
3,Ce livre devrait me permettre de résoudre le c...,"Mazas, Sylvain, 1980-",9782365350020; 236535002X; 9782365350488; 2365...,Vraoum!,Moyen-Orient; Bandes dessinées autobiographiqu...,3
4,Les années glorieuses : roman /,"Lemaitre, Pierre, 1951-",9782702180815; 2702180817; 9782702183618; 2702...,Calmann-Lévy,France--1945-1975; Roman historique; Roman fra...,4

In [ ]:
# User-item interaction matrix
user_item_matrix = interactions_train.groupby(['u', 'i'])['t'].sum().unstack().fillna(0)

# Générer des recommandations
def get_top_n_recommendations(user_prediction, n=10):
    recommendations = []
    for user_id in user_prediction.index:
        user_scores = user_prediction.loc[user_id]
        top_items = user_scores.sort_values(ascending=False).head(n).index.tolist()
        recommendations.append({'user_id': user_id, 'recommendation': ' '.join(map(str, top_items))})
    return recommendations

# Le top 10 des recommendations
top_recommendations = get_top_n_recommendations(user_item_matrix, n=10)

# Dataframe pour les recommandations finales
final_recommendations = pd.DataFrame(top_recommendations)

# Recommandation en CSV
final_recommendations.to_csv("submission.csv", index=False, sep=",", quotechar="", quoting=3)
print("Fichier CSV 'submission.csv' généré avec succès.")

Fichier CSV 'submission.csv' généré avec succès.

In [ ]:
from google.colab import files

# Télécharger le fichier généré
files.download("submission.csv")